name: listify
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: 0.1.3
  momentum: ^1.3.6
  equatable: 1.1.1
  shared_preferences: 0.5.7+3
  fluttertoast: 7.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
